name: 'Test main'
on:
  [ pull_request, push ]
  #   pull_request:
  #     branches:
  #       - main
  #   push:
  #     branches:
  #       - main
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install nix
      uses: cachix/install-nix-action@v25
        #    - name: Run go linter
        #      run: nix develop --command lint_go
    - name: Run go tests
      run: |
        test_logs=./.test_logs
        mkdir -p "$test_logs"
        nix develop --command test_go -o "$test_logs/$GITHUB_SHA"
    - name: Write repository
      env:
        MY_PERSONAL_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
      run: |
        git config --global user.email "marvin1995mann@gmail.com"
        git config --global user.name "maff9n"
        git remote add gitlab_origin https://maff9n:$MY_PERSONAL_TOKEN@github.com:maff9n/go_githubCI.git
        git add .
        git commit -m "push back from pipeline"
        git push gitlab_origin HEAD:main -o ci.skip
