name: 'Test main'
on:
  [ pull_request, push ]
  #   pull_request:
  #     branches:
  #       - main
  #   push:
  #     branches:
  #       - main
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install nix
      uses: cachix/install-nix-action@v25
    - name: Run go linter
      run: nix develop --command lint_go
    - name: Run go tests
      run: |
        test_logs=./.test_logs
        mkdir -p "$test_logs"
        nix develop --command test_go -o "$test_logs/$GITHUB_SHA"
